version: '3.7'

services:
  backend:
    build: .
    container_name: bank-backend
#    environment:
    ports:
      - "8084:8084"
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: user
#    volumes:
#      - data_sql:/var/lib/postgresql
