version: '3.7'

services:
  backend:
    build: .
    container_name: bank-backend
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_LIQUIBASE_URL: ${SPRING_LIQUIBASE_URL}
      SPRING_LIQUIBASE_USER: ${SPRING_LIQUIBASE_USER}
      SPRING_LIQUIBASE_PASSWORD: ${SPRING_LIQUIBASE_PASSWORD}
      SPRING_LIQUIBASE_PARAMETERS_SYSTEM_ADMIN_PASSWORD_HASH: ${SPRING_LIQUIBASE_PARAMETERS_SYSTEM_ADMIN_PASSWORD_HASH}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    ports:
      - "8084:8084"
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
#    volumes:
#      - data_sql:/var/lib/postgresql
