spring.application.name=bankEffectiveMobile

server.port=8084

spring.datasource.url=jdbc:postgresql://10.10.10.61:5432/user
spring.datasource.username=user
spring.datasource.password=user

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.url=jdbc:postgresql://10.10.10.61:5432/user
spring.liquibase.user=user
spring.liquibase.password=user
spring.liquibase.parameters.system_admin_password_hash=$2a$10$6tAWZNv7mz.o9fPV9BtegeFZpB7e2CcLex4UE/QU9C6Cfp2R3jbuW

jwt.secret=mySecretKeyForJwtTokenGeneration123456789012
jwt.expiration=86400000
