spring.application.name=bankEffectiveMobile
server.port=8084
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.url=${SPRING_LIQUIBASE_URL}
spring.liquibase.user=${SPRING_LIQUIBASE_USER}
spring.liquibase.password=${SPRING_LIQUIBASE_PASSWORD}
spring.liquibase.parameters.system_admin_password_hash=${SPRING_LIQUIBASE_PARAMETERS_SYSTEM_ADMIN_PASSWORD_HASH}
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
